# -*- coding: utf-8 -*-
"""Copie de multiple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IVKj9izt3nf5M6Mc1IlyhZPSKUelv58

# Multiple Linear Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

"""## Importing the dataset"""

dataset = pd.read_excel('/home/saad/Documents/PROJECT_flask/salaire.xlsx')
X = dataset.iloc[:, [1,3,4]].values
y = dataset.iloc[:, 2].values

"""## Encoding categorical data"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

"""## Training the Multiple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

pickle.dump(regressor, open("PROJECT_flask/model.pkl", "wb"))

